name: mirror

on: 
  workflow_dispatch:

jobs:
  mirror:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: mirror
      run: ./mirror.sh
      env:
        WIKI_PERSONAL_ACCESS_TOKENL{{ secrets.WIKI_PERSONAL_ACCESS_TOKEN }}
