name: mirror

on: 
  repository_dispatch:
    types: [mirror]

jobs:
  mirror:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: mirror
      run: ./mirror.sh
      env:
        WIKI_PERSONAL_ACCESS_TOKEN: ${{ secrets.WIKI_PERSONAL_ACCESS_TOKEN }}
